// Tipos exportados
export interface Contact {
	phone?: string;
	phoneClick?: string;
	email?: string;
	url?: string;
	verifiedAt: string;
}

export interface Entry {
	id: string;
	type: string;
	title: string;
	description: string;
	contact: Contact;
	tags: string[];
	sources: string[];
	notes?: string;
}

export interface Region {
	level: 'national' | 'state' | 'city';
	name: string;
	stateCode?: string;
	cityCode?: string;
	entries: Entry[];
}

// Dados centralizados
export const REGIONS_DATA: Region[] = [
	{
		level: 'national',
		name: 'Brasil',
		entries: [
			{
				id: 'br-0001',
				type: 'emergência',
				title: 'Polícia Militar (Emergência)',
				description: 'Número de emergência para ocorrências policiais em todo o Brasil.',
				contact: {
					phone: '190',
					phoneClick: 'tel:190',
					verifiedAt: '2025-11-23',
				},
				tags: ['polícia', 'emergência', '190'],
				sources: [],
				notes: 'Número nacional de emergência policial; pode haver ramais locais.',
			},
			{
				id: 'br-0002',
				type: 'saúde',
				title: 'SAMU - Atendimento Móvel de Urgência',
				description: 'Atendimento pré-hospitalar de urgência médica em todo o Brasil.',
				contact: {
					phone: '192',
					phoneClick: 'tel:192',
					url: 'https://www.gov.br/saude/pt-br/composicao/saes/samu-192',
					verifiedAt: '2025-11-23',
				},
				tags: ['saúde', 'emergência', '192'],
				sources: ['https://www.gov.br/saude/pt-br/composicao/saes/samu-192'],
				notes: 'Serviço 24h disponível em todo o país.',
			},
			{
				id: 'br-0003',
				type: 'fogo',
				title: 'Corpo de Bombeiros',
				description: 'Atendimento a incêndios, salvamentos e acidentes.',
				contact: {
					phone: '193',
					phoneClick: 'tel:193',
					verifiedAt: '2025-11-23',
				},
				tags: ['bombeiros', 'fogo', '193'],
				sources: [],
				notes: '193 é o número padrão nacional.',
			},
			{
				id: 'br-0004',
				type: 'aconselhamento',
				title: 'CVV - Centro de Valorização da Vida',
				description: 'Atendimento emocional 24h para prevenção do suicídio, gratuito.',
				contact: {
					phone: '188',
					phoneClick: 'tel:188',
					url: 'https://cvv.org.br/',
					verifiedAt: '2025-11-23',
				},
				tags: ['saúde', 'aconselhamento', '188'],
				sources: ['https://cvv.org.br/'],
				notes: 'Atendimento gratuito por voluntários 24 horas.',
			},
			{
				id: 'br-0005',
				type: 'direitos_humanos',
				title: 'Disque Direitos Humanos (Disque 100)',
				description: 'Canal nacional para denúncias de violações de direitos humanos.',
				contact: {
					phone: '100',
					phoneClick: 'tel:100',
					url: 'https://www.gov.br/pt-br/servicos/denunciar-violacao-de-direitos-humanos',
					verifiedAt: '2025-11-23',
				},
				tags: ['direitos_humanos', 'disque100', 'denuncia'],
				sources: ['https://www.gov.br/pt-br/servicos/denunciar-violacao-de-direitos-humanos'],
				notes: 'Atendimento gratuito com possibilidade de anonimato.',
			},
			{
				id: 'br-0006',
				type: 'violência_contra_mulher',
				title: 'Central de Atendimento à Mulher (Ligue 180)',
				description: 'Canal de utilidade pública para enfrentamento à violência contra a mulher.',
				contact: {
					phone: '180',
					phoneClick: 'tel:180',
					url: 'https://www.gov.br/mulheres/pt-br/ligue180',
					verifiedAt: '2025-11-23',
				},
				tags: ['violência_contra_mulher', '180', 'hotline'],
				sources: ['https://www.gov.br/mulheres/pt-br/ligue180'],
				notes: 'Atendimento 24h, gratuito, com possibilidade de registro e encaminhamento.',
			},
			{
				id: 'br-0007',
				type: 'proteção_a_criança',
				title: 'Disque 100 - Proteção de Crianças e Adolescentes',
				description: 'Denúncias de violência sexual e abuso de crianças.',
				contact: {
					phone: '100',
					phoneClick: 'tel:100',
					url: 'https://www.gov.br/pt-br/servicos/denunciar-violacao-de-direitos-humanos',
					verifiedAt: '2025-11-23',
				},
				tags: ['proteção_a_criança', 'disque100'],
				sources: ['https://www.gov.br/pt-br/servicos/denunciar-violacao-de-direitos-humanos'],
				notes: 'O Disque 100 também recebe denúncias de violência sexual contra crianças.',
			},
			{
				id: 'br-0008',
				type: 'transparência',
				title: 'Portal da Transparência (CGU)',
				description: 'Acesso a dados públicos federais, transferências e convênios.',
				contact: {
					url: 'https://portaldatransparencia.gov.br/',
					verifiedAt: '2025-11-23',
				},
				tags: ['transparência', 'cgu', 'dados'],
				sources: ['https://portaldatransparencia.gov.br/'],
				notes: 'Use para consultar gastos públicos e contratos.',
			},
			{
				id: 'br-0009',
				type: 'legislativo',
				title: 'Câmara dos Deputados - Portal',
				description: 'Acesso a proposições, pauta, tramitação de projetos de lei e participação pública.',
				contact: {
					url: 'https://www.camara.leg.br/',
					verifiedAt: '2025-11-23',
				},
				tags: ['legislativo', 'camara', 'participação'],
				sources: ['https://www.camara.leg.br/'],
				notes: 'Permite acompanhar votações, autores e tramitação de projetos.',
			},
			{
				id: 'br-0010',
				type: 'legislativo',
				title: 'Senado Federal - Portal',
				description: 'Acompanhe projetos, senadores, emendas e sessões legislativas.',
				contact: {
					url: 'https://www25.senado.leg.br/web/atividade/materias',
					verifiedAt: '2025-11-23',
				},
				tags: ['legislativo', 'senado', 'participação'],
				sources: ['https://www25.senado.leg.br/web/atividade/materias'],
				notes: 'Informações sobre votações e tramitação no Senado.',
			},
			{
				id: 'br-0011',
				type: 'eleitoral',
				title: 'Tribunal Superior Eleitoral (TSE)',
				description: 'Informações sobre cadastro eleitoral, locais de votação e candidatos.',
				contact: {
					url: 'https://www.tse.jus.br/eleitor',
					verifiedAt: '2025-11-23',
				},
				tags: ['eleitoral', 'voting', 'tse'],
				sources: ['https://www.tse.jus.br/eleitor'],
				notes: 'Portal oficial com ferramentas de consulta ao eleitor.',
			},
			{
				id: 'br-0013',
				type: 'ouvidoria',
				title: 'Ouvidoria-Geral da União (OGU)',
				description: 'Canal para manifestações ao governo federal (reclamações, elogios, denúncias).',
				contact: {
					url: 'https://www.gov.br/secretariageral/pt-br/assuntos/ouvidoria',
					verifiedAt: '2025-11-23',
				},
				tags: ['ouvidoria', 'governo', 'manifestacao'],
				sources: ['https://www.gov.br/secretariageral/pt-br/assuntos/ouvidoria'],
				notes: 'Use para encaminhar reclamações sobre serviços federais.',
			},
		],
	},
	{
		level: 'state',
		name: 'São Paulo',
		stateCode: 'SP',
		entries: [
			{
				id: 'sp-001',
				type: 'polícia',
				title: 'Polícia Militar de São Paulo',
				description: 'Emergência policial no estado de São Paulo.',
				contact: {
					phone: '190',
					phoneClick: 'tel:190',
					url: 'https://www.policiamilitar.sp.gov.br/',
					verifiedAt: '2025-11-23',
				},
				tags: ['polícia', 'sp', '190'],
				sources: ['https://www.policiamilitar.sp.gov.br/'],
				notes: 'Portal oficial da PM-SP com telefones úteis e unidades.',
			},
			{
				id: 'sp-002',
				type: 'polícia',
				title: 'Polícia Civil de São Paulo',
				description: 'Informações sobre delegacias especializadas e boletins de ocorrência.',
				contact: {
					phone: '197',
					phoneClick: 'tel:197',
					url: 'https://www.policiacivil.sp.gov.br/',
					verifiedAt: '2025-11-23',
				},
				tags: ['polícia', 'civil', 'sp'],
				sources: ['https://www.policiacivil.sp.gov.br/'],
				notes: 'Verifique delegacia local para BO online.',
			},
			{
				id: 'sp-003',
				type: 'violência_contra_mulher',
				title: 'Delegacia de Defesa da Mulher - SP',
				description: 'Rede de delegacias especializadas para atendimento às mulheres.',
				contact: {
					url: 'https://www.policiacivil.sp.gov.br/',
					verifiedAt: '2025-11-23',
				},
				tags: ['delegacia_da_mulher', 'sp', 'women'],
				sources: ['https://www.policiacivil.sp.gov.br/'],
				notes: 'Consulte o site da Polícia Civil para localizar a delegacia mais próxima.',
			},
			{
				id: 'sp-004',
				type: 'fogo',
				title: 'Corpo de Bombeiros Militar de São Paulo',
				description: 'Emergências de incêndio, resgate e acidentes.',
				contact: {
					phone: '193',
					phoneClick: 'tel:193',
					url: 'https://www.bombeiros.sp.gov.br/',
					verifiedAt: '2025-11-23',
				},
				tags: ['fogo', 'rescue', 'sp', '193'],
				sources: ['https://www.bombeiros.sp.gov.br/'],
				notes: 'Atendimento 24h para incêndios e salvamentos.',
			},
			{
				id: 'sp-005',
				type: 'saúde',
				title: 'SAMU - São Paulo',
				description: 'Atendimento móvel de urgência médica em São Paulo.',
				contact: {
					phone: '192',
					phoneClick: 'tel:192',
					verifiedAt: '2025-11-23',
				},
				tags: ['saúde', 'ambulancia', 'sp', '192'],
				sources: [],
				notes: 'Serviço de atendimento pré-hospitalar 24h.',
			},
			{
				id: 'sp-006',
				type: 'transparência',
				title: 'Portal da Transparência - SP',
				description: 'Consulta a gastos, contratos e informações públicas estaduais.',
				contact: {
					url: 'https://www.transparencia.sp.gov.br/',
					verifiedAt: '2025-11-23',
				},
				tags: ['transparência', 'sp'],
				sources: ['https://www.transparencia.sp.gov.br/'],
				notes: 'Ferramenta para controle social dos gastos estaduais.',
			},
			{
				id: 'sp-007',
				type: 'participação',
				title: 'Assembleia Legislativa do Estado de São Paulo (Alesp)',
				description: 'Acompanhe proposições estaduais e canais de contato com deputados.',
				contact: {
					url: 'https://www.al.sp.gov.br/',
					verifiedAt: '2025-11-23',
				},
				tags: ['legislativo', 'alesp', 'sp'],
				sources: ['https://www.al.sp.gov.br/'],
				notes: 'Ferramentas para acompanhar tramitação e contato com deputados.',
			},
			{
				id: 'sp-008',
				type: 'proteção_ao_consumidor',
				title: 'Procon-SP',
				description: 'Órgão de proteção e defesa do consumidor do estado de São Paulo.',
				contact: {
					phone: '151',
					phoneClick: 'tel:151',
					url: 'https://www.procon.sp.gov.br/',
					verifiedAt: '2025-11-23',
				},
				tags: ['procon', 'proteção_ao_consumidor', 'sp'],
				sources: ['https://www.procon.sp.gov.br/'],
				notes: 'Atendimento para reclamações de consumo; ligue 151 para denúncias.',
			},
			{
				id: 'sp-009',
				type: 'ouvidoria',
				title: 'Ouvidoria do Estado de São Paulo',
				description: 'Canal de reclamações, sugestões e denúncias contra órgãos públicos.',
				contact: {
					phone: '0800 017 0777',
					phoneClick: 'tel:0800-017-0777',
					url: 'https://www.ouvidoria.sp.gov.br/',
					verifiedAt: '2025-11-23',
				},
				tags: ['ouvidoria', 'sp', 'reclamacao'],
				sources: ['https://www.ouvidoria.sp.gov.br/'],
				notes: 'Atendimento gratuito para manifestações contra administração pública.',
			},
			{
				id: 'sp-010',
				type: 'eleitoral',
				title: 'Tribunal Regional Eleitoral de São Paulo',
				description: 'Informações sobre eleições, títulos eleitorais e votação.',
				contact: {
					url: 'https://www.tre-sp.jus.br/',
					verifiedAt: '2025-11-23',
				},
				tags: ['eleitoral', 'tre', 'sp'],
				sources: ['https://www.tre-sp.jus.br/'],
				notes: 'Informações sobre processo eleitoral em São Paulo.',
			},
		],
	},
	{
		level: 'state',
		name: 'Rio de Janeiro',
		stateCode: 'RJ',
		entries: [
			{
				id: 'rj-001',
				type: 'polícia',
				title: 'Polícia Militar do Estado do Rio de Janeiro',
				description: 'Emergência policial no RJ.',
				contact: {
					phone: '190',
					phoneClick: 'tel:190',
					url: 'https://www.policiamilitar.rj.gov.br/',
					verifiedAt: '2025-11-23',
				},
				tags: ['polícia', 'rj'],
				sources: ['https://www.policiamilitar.rj.gov.br/'],
				notes: 'Portal oficial da PM-RJ.',
			},
			{
				id: 'rj-002',
				type: 'polícia',
				title: 'Polícia Civil do Estado do Rio de Janeiro',
				description: 'Informações sobre delegacias e serviços online.',
				contact: {
					phone: '197',
					phoneClick: 'tel:197',
					url: 'https://www.policiacivil.rj.gov.br/',
					verifiedAt: '2025-11-23',
				},
				tags: ['polícia', 'civil', 'rj'],
				sources: ['https://www.policiacivil.rj.gov.br/'],
				notes: 'Verificar delegacia local para BO e atendimento especializado.',
			},
			{
				id: 'rj-003',
				type: 'transparência',
				title: 'Portal da Transparência - RJ',
				description: 'Consulta pública de gastos e contratos do estado.',
				contact: {
					url: 'https://www.transparencia.rj.gov.br/',
					verifiedAt: '2025-11-23',
				},
				tags: ['transparência', 'rj'],
				sources: ['https://www.transparencia.rj.gov.br/'],
				notes: 'Acesso a informações fiscais e contratuais.',
			},
			{
				id: 'rj-004',
				type: 'participação',
				title: 'Assembleia Legislativa do Estado do Rio de Janeiro (Alerj)',
				description: 'Tramitação de proposições e contato com deputados estaduais.',
				contact: {
					url: 'https://www.alerj.rj.gov.br/',
					verifiedAt: '2025-11-23',
				},
				tags: ['legislativo', 'alerj', 'rj'],
				sources: ['https://www.alerj.rj.gov.br/'],
				notes: 'Ferramentas para acompanhar projetos de lei estaduais.',
			},
			{
				id: 'rj-005',
				type: 'fogo',
				title: 'Corpo de Bombeiros Militar do RJ',
				description: 'Serviços de incêndio, resgate e emergências no RJ.',
				contact: {
					phone: '193',
					phoneClick: 'tel:193',
					url: 'https://www.bombeiros.rj.gov.br/',
					verifiedAt: '2025-11-23',
				},
				tags: ['fogo', 'rescue', 'rj', '193'],
				sources: ['https://www.bombeiros.rj.gov.br/'],
				notes: 'Chamadas de emergência via 193 disponível 24h.',
			},
			{
				id: 'rj-006',
				type: 'proteção_ao_consumidor',
				title: 'Procon-RJ',
				description: 'Proteção ao consumidor no estado do Rio de Janeiro.',
				contact: {
					url: 'https://www.procon.rj.gov.br/',
					verifiedAt: '2025-11-23',
				},
				tags: ['procon', 'proteção_ao_consumidor', 'rj'],
				sources: ['https://www.procon.rj.gov.br/'],
				notes: 'Atendimento a reclamações e denúncias de consumo.',
			},
			{
				id: 'rj-007',
				type: 'saúde',
				title: 'SAMU - Rio de Janeiro',
				description: 'Atendimento móvel de urgência médica no estado.',
				contact: {
					phone: '192',
					phoneClick: 'tel:192',
					verifiedAt: '2025-11-23',
				},
				tags: ['saúde', 'ambulancia', 'rj', '192'],
				sources: [],
				notes: 'Serviço de atendimento pré-hospitalar 24h.',
			},
			{
				id: 'rj-008',
				type: 'ouvidoria',
				title: 'Ouvidoria do Estado do Rio de Janeiro',
				description: 'Canal de reclamações e denúncias contra órgãos públicos.',
				contact: {
					phone: '0800 282 8282',
					phoneClick: 'tel:0800-282-8282',
					url: 'https://www.ouvidoria.rj.gov.br/',
					verifiedAt: '2025-11-23',
				},
				tags: ['ouvidoria', 'rj'],
				sources: ['https://www.ouvidoria.rj.gov.br/'],
				notes: 'Atendimento gratuito para manifestações públicas.',
			},
			{
				id: 'rj-009',
				type: 'violência_contra_mulher',
				title: 'Polícia da Mulher - RJ',
				description: 'Delegacias especializadas no atendimento às mulheres.',
				contact: {
					url: 'https://www.policiacivil.rj.gov.br/',
					verifiedAt: '2025-11-23',
				},
				tags: ['delegacia_da_mulher', 'rj', 'women'],
				sources: ['https://www.policiacivil.rj.gov.br/'],
				notes: 'Rede de atendimento especializado para mulheres em situação de violência.',
			},
			{
				id: 'rj-010',
				type: 'eleitoral',
				title: 'Tribunal Regional Eleitoral do RJ',
				description: 'Informações sobre eleições e processo eleitoral.',
				contact: {
					url: 'https://www.tre-rj.jus.br/',
					verifiedAt: '2025-11-23',
				},
				tags: ['eleitoral', 'tre', 'rj'],
				sources: ['https://www.tre-rj.jus.br/'],
				notes: 'Portal com informações sobre votação e títulos eleitorais.',
			},
		],
	},
	{
		level: 'state',
		name: 'Minas Gerais',
		stateCode: 'MG',
		entries: [
			{
				id: 'mg-001',
				type: 'polícia',
				title: 'Polícia Militar de Minas Gerais',
				description: 'Emergência policial no estado de Minas Gerais.',
				contact: {
					phone: '190',
					phoneClick: 'tel:190',
					url: 'https://www.policiamilitar.mg.gov.br/',
					verifiedAt: '2025-11-23',
				},
				tags: ['polícia', 'mg'],
				sources: ['https://www.policiamilitar.mg.gov.br/'],
				notes: 'Portal oficial da PM-MG com telefones e instruções.',
			},
			{
				id: 'mg-002',
				type: 'polícia',
				title: 'Polícia Civil de Minas Gerais',
				description: 'Informações sobre delegacias especializadas.',
				contact: {
					phone: '197',
					phoneClick: 'tel:197',
					url: 'https://www.policiacivil.mg.gov.br/',
					verifiedAt: '2025-11-23',
				},
				tags: ['polícia', 'civil', 'mg'],
				sources: ['https://www.policiacivil.mg.gov.br/'],
				notes: 'Verifique delegacia local para atendimento e BO presencial.',
			},
			{
				id: 'mg-003',
				type: 'transparência',
				title: 'Portal de Transparência - MG',
				description: 'Acesso a gastos públicos e contratos do estado.',
				contact: {
					url: 'https://www.transparencia.mg.gov.br/',
					verifiedAt: '2025-11-23',
				},
				tags: ['transparência', 'mg'],
				sources: ['https://www.transparencia.mg.gov.br/'],
				notes: 'Portal da transparência para controle social de gastos.',
			},
			{
				id: 'mg-004',
				type: 'participação',
				title: 'Assembleia Legislativa de Minas Gerais (ALMG)',
				description: 'Tramitação de projetos de lei e contato com deputados estaduais.',
				contact: {
					url: 'https://www.almg.gov.br/',
					verifiedAt: '2025-11-23',
				},
				tags: ['legislativo', 'almg', 'mg'],
				sources: ['https://www.almg.gov.br/'],
				notes: 'Ferramentas para acompanhar projetos e deputados.',
			},
			{
				id: 'mg-005',
				type: 'fogo',
				title: 'Corpo de Bombeiros Militar de Minas Gerais',
				description: 'Emergências de incêndio, resgate e acidentes.',
				contact: {
					phone: '193',
					phoneClick: 'tel:193',
					url: 'https://www.cbmmg.mg.gov.br/',
					verifiedAt: '2025-11-23',
				},
				tags: ['fogo', 'rescue', 'mg', '193'],
				sources: ['https://www.cbmmg.mg.gov.br/'],
				notes: 'Chamadas de emergência 24h através do número 193.',
			},
			{
				id: 'mg-006',
				type: 'proteção_ao_consumidor',
				title: 'Procon-MG',
				description: 'Proteção e defesa do consumidor em Minas Gerais.',
				contact: {
					url: 'https://www.procon.mg.gov.br/',
					verifiedAt: '2025-11-23',
				},
				tags: ['procon', 'proteção_ao_consumidor', 'mg'],
				sources: ['https://www.procon.mg.gov.br/'],
				notes: 'Reclamações e denúncias de abuso do consumidor.',
			},
			{
				id: 'mg-007',
				type: 'saúde',
				title: 'SAMU - Minas Gerais',
				description: 'Atendimento móvel de urgência médica no estado.',
				contact: {
					phone: '192',
					phoneClick: 'tel:192',
					verifiedAt: '2025-11-23',
				},
				tags: ['saúde', 'ambulancia', 'mg', '192'],
				sources: [],
				notes: 'Serviço de atendimento pré-hospitalar disponível 24h.',
			},
			{
				id: 'mg-008',
				type: 'ouvidoria',
				title: 'Ouvidoria Única do Estado de Minas Gerais',
				description: 'Canal único de reclamações e sugestões ao governo.',
				contact: {
					phone: '155',
					phoneClick: 'tel:155',
					url: 'https://www2.ouvidoria.mg.gov.br/',
					verifiedAt: '2025-11-23',
				},
				tags: ['ouvidoria', 'mg', '155'],
				sources: ['https://www2.ouvidoria.mg.gov.br/'],
				notes: 'Atendimento por telefone, email ou presencialmente em polos.',
			},
			{
				id: 'mg-009',
				type: 'violência_contra_mulher',
				title: 'Delegacia de Atendimento à Mulher - MG',
				description: 'Especializadas em violência doméstica e sexual.',
				contact: {
					url: 'https://www.policiacivil.mg.gov.br/',
					verifiedAt: '2025-11-23',
				},
				tags: ['delegacia_da_mulher', 'mg', 'women'],
				sources: ['https://www.policiacivil.mg.gov.br/'],
				notes: 'Rede de atendimento especializado para mulheres vítimas de violência.',
			},
			{
				id: 'mg-010',
				type: 'eleitoral',
				title: 'Tribunal Regional Eleitoral de Minas Gerais',
				description: 'Informações sobre eleições e processo eleitoral em MG.',
				contact: {
					url: 'https://www.tre-mg.jus.br/',
					verifiedAt: '2025-11-23',
				},
				tags: ['eleitoral', 'tre', 'mg'],
				sources: ['https://www.tre-mg.jus.br/'],
				notes: 'Portal oficial com informações sobre votação e títulos eleitorais.',
			},	
		],
	},
];